# Generated by Django 5.1.15 on 2026-04-30 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='developerprofile',
            name='github_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='developerprofile',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
